export const ADD_NEW_COURSE = 'ADD_NEW_COURSE';
export const UPDATE_COURSE = 'UPDATE_COURSE';
export const DELETE_COURSE = 'DELETE_COURSE';
export const CHANGE_COURCES_NUMBER_ON_PAGE = 'CHANGE_COURCES_NUMBER_ON_PAGE';
export const ADD_NEW_STUDENT = 'ADD_NEW_STUDENT';
export const UPDATE_STUDENT = 'UPDATE_STUDENT';
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const CHANGE_STUDENTS_NUMBER_ON_PAGE = 'CHANGE_STUDENTS_NUMBER_ON_PAGE';
