export const GET_INIT_DATA = ' GET_INIT_DATA';

// export const START_FETCH_PLAYERS = ' START_FETCH_PLAYERS';
// export const END_FETCH_PLAYERS = ' END_FETCH_PLAYERS';
// export const CLEAR_PLAYERS = ' CLEAR_PLAYERS';
// export const START_FETCH_TRANSFERS = ' START_FETCH_TRANSFERS';
// export const END_FETCH_TRANSFERS = ' END_FETCH_TRANSFERS';
// export const CLEAR_TRANSFERS = ' CLEAR_TRANSFERS';
// export const START_SET_TRAINING = ' START_SET_TRAINING';
// export const END_SET_TRAINING = ' END_SET_TRAINING';
// export const START_SEARCH_PLAYERS = ' START_SEARCH_PLAYERS';
// export const END_SEARCH_PLAYERS = ' END_SEARCH_PLAYERS';
// export const CLEAR_SEARCH = ' CLEAR_SEARCH';
// export const CLEAR_SEARCH_FILTER = ' CLEAR_SEARCH_FILTER';
// export const MARK_NEWS = ' MARK_NEWS';
