name: Slash commands

on:
  issue_comment:
    types: [created, deleted]

jobs:
  check_comments:
    name: Run integration tests on /ci
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/')
    runs-on: ubuntu-latest
    steps:
      - name: Check for Command
        id: command
        uses: xt0rted/slash-command-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          command: ci
          reaction-type: "eyes"
      - name: Show parsed command and arguments
        run: echo "The command was '${{ steps.command.outputs.command-name }}' with arguments '${{ steps.command.outputs.command-arguments }}'"
      - uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch
#       - name: Run integration tests
#         run: |
#           echo "Starting integration tests..."
#           echo "PR #${{ github.event.issue.number }}"
#           echo "SHA - ${{ steps.comment-branch.outputs.head_sha }}"
#           echo "Ref - ${{ steps.comment-branch.outputs.head_ref }}"
#           echo "Ref1 - ${{ github.event.issue.pull_request.head.ref }}"
#       - name: Unknown command
#         if: ${{steps.command.outputs.command-arguments != 'cypress' && steps.command.outputs.command-arguments != 'integration-tests'}}
#         run: echo "Unknown command"
        
#       - name: Run workflow
#         uses: benc-uk/workflow-dispatch@v1
#         with:
#           workflow: Post_message
#           token: ${{ secrets.PERSONAL_TOKEN }}
#           ref: ${{ steps.comment-branch.outputs.head_ref }}
#           inputs: '{ "ref": "blah blah"}'
          
#           ref: ${{ steps.comment-branch.outputs.head_sha }}
#           ref: ${{ github.event.issue.pull_request.head.ref }}

      - name: View context attributes
        uses: actions/github-script@v4
        with:
          script: console.log(context.repo)
          
      - name: Starting test comment
        if: ${{steps.command.outputs.command-arguments == 'cypress' || steps.command.outputs.command-arguments == 'integration-tests'}}
        id: add-comment
        uses: actions/github-script@v4
        with:
          script: |
            return github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '####Starting tests... \n\n *This comment will be updated after testing is complete*'
            })
            
      - name: Get add-comments result
        run: echo "${{steps.add-comment.outputs.result.body.id}}"
            
      - name: Invoke workflow and handle result
        id: trigger-step
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: Post_message
          token: ${{ secrets.PERSONAL_TOKEN }}
          inputs: '{ "issue_number": "${{github.event.issue.number}}", "runId": "${{github.event.runId}}"}'
      
      - name: Get workflow result
        run: echo "${{steps.add-comment.outputs.result}}"
        
      - name: Post a result comment
        if: always()
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Test finished with' + context.steps.trigger-step.outputs.workflow-conclusion + 'status
            })

