name: Slash commands

on:
  issue_comment:
    types: [created, deleted]

jobs:
  check_comments:
    name: Run integration tests on /ci
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/')
    runs-on: ubuntu-latest
    steps:
      - name: Check for Command
        id: command
        uses: xt0rted/slash-command-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          command: ci
          reaction-type: "eyes"
      - name: Show parsed command and arguments
        run: echo "The command was '${{ steps.command.outputs.command-name }}' with arguments '${{ steps.command.outputs.command-arguments }}'"
      - name: Run integration tests
        if: ${{steps.command.outputs.command-arguments == 'cypress' || steps.command.outputs.command-arguments == 'integration-tests'}}
        run: echo "Starting integration tests..."
      - name: Unknown command
        if: ${{steps.command.outputs.command-arguments != 'cypress' && steps.command.outputs.command-arguments != 'integration-tests'}}
        run: echo "Unknown command"
      - name: Run workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Post message in PR
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}
