name: Pull request size

on:
  pull_request:
    types: [opened, reopened, synchronize]

env:
  PR_MAX_SIZE: "4"

jobs:
  pr-size:
    runs-on: ubuntu-latest
    steps:
      - name: Check for ignore comment
        id: ignore
        uses: actions/github-script@v5
        with:
          script: |
            const comments = await github.rest.issues.listComments({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            }).then(({data}) => data)
            return comments.some(({body}) => body === "/ignore pr-size")

      - name: Set failure
        if: |
          !steps.ignore.outputs.result 

        run: |
          echo "PR size more than ${{ env.PR_MAX_SIZE }}"
          exit 1
