name: WIP-commits

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

jobs:
  wip-commits:
    runs-on: ubuntu-latest
    steps:
#        - name: Convert to Draft
#          run: |
#           echo ${{github.event.action}}
#           echo ${{github.event.type}}
#           echo ${{github.pull_request.action}}
#           echo ${{github.pull_request.type}}
       - name: Get WIP-commits
         id: get-wip-commits
         if: ${{!github.event.pull_request.draft}}
         uses: actions/github-script@v4
         with:
          script: |
            const wipCommits = await github.pulls.listCommits({
              owner: context.issue.owner,
              repo: context.issue.repo,
              pull_number: context.issue.number,
            }).then(({data}) => data.filter(({commit}) => commit.message === 'WIP'))
            return wipCommits.length ? wipCommits : null
          
       - name: Set failure
         if: ${{steps.get-wip-commits.outputs.result}}
         run: |
           echo "WIP-commits found"
           exit 1
           
       - name: Convert to Draft
         if: failure()
         env:
            WIP_COMMITS: ${{steps.get-wip-commits.outputs.result}}
         uses: actions/github-script@v4
         with:
          script: |
            const { WIP_COMMITS } = process.env    
            console.log("+++++++")
            console.log(WIP_COMMITS)
            console.log("=======")
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.issue.owner,
              repo: context.issue.repo,
              body: `#### WIP commits:${WIP_COMMITS.forEach(({sha, html_url}) => `\n\n- [${sha}](${html_url})`)}`
            })
            
      #.map(({commit}) => commit.html_url));
            
    #    console.log(context)
     #       console.log("================================")
     
     
     

